######
# Colin Powell
# CS362: Random Testing quiz
# Makefile
######



CFLAGS = -Wall -fpic -coverage -std=c99
CXX = gcc
PROG = testme

default: 
	${CXX} -o ${PROG} testme.c ${CFLAGS}

clean:
	rm testme
